FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY Data-Provider-Service ./Data-Provider-Service

CMD ["uvicorn", "Data-Provider-Service.dataprovider:app", "--host", "0.0.0.0", "--port", "8000"]