FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY Dashboard-Service ./Dashboard-Service

CMD ["uvicorn", "Dashboard-Service.dashboard:app", "--host", "0.0.0.0", "--port", "7777"]